- type: PhaseQuestion
  internalName: Entry
  questions:
    - type: QuestionFreeForm
      ask: What's broken?
      placeholderText: e.g. "it shows wrong OD scores"
      minResponseLength: 10
