- type: PhaseQuestion
  internalName: Entry
  questions:
    - type: QuestionFreeForm
      ask: What's broken?
      placeholderText: e.g. "it doesn't focus the Start button"
      minResponseLength: 10
