import { Command } from '/twcheese/src/Models/Command.js';
import { parseArrival } from '/twcheese/src/Scrape/time.js';
import { scrapeResources } from '/twcheese/src/Scrape/res.js';

/**
 *	scrapes a command page for the command info and returns it as a Command object
 *	@param	{HTMLDocument} gameDoc	the page generated by game.php?screen=command_info&id=x&type=own
 *	@return {Command}
 */
function scrapeCommand(gameDoc) {
    var command = new Command();
    
    var content = $(gameDoc).find('#content_value').get()[0];
    let tables = content.getElementsByTagName('table');

    let arrivalCell = tables[0].rows[6].cells[1];
    command.arrival = parseArrival($(arrivalCell).text());

    if (tables.length < 3) {
        return command;
    }

    let resCell = tables[2].rows[0].cells[1];
    command.haul = scrapeResources(resCell);

    var haulText = resCell.innerHTML;
    if (haulText.search('\\|') !== -1) {
        haulText = haulText.substring(haulText.search('\\|') + 7);
        let performance = haulText.split('/');
        command.haulCapacity = parseInt(performance[1]);
    }

    return command;
};


function scrapeCommandUrlFromRow(row) {
    let firstCell = row.cells[0];
    let links = firstCell.getElementsByTagName('a');
    if (links.length < 1) {
        throw `failed to find command link`;
    }
    return links[0].href;
}


export { scrapeCommand, scrapeCommandUrlFromRow } 