- type: PhaseQuestion
  internalName: Entry
  questions:
    - type: QuestionFreeForm
      ask: What's broken?
      placeholderText: e.g. "it freezes when loading hauls"
      minResponseLength: 10
